Added new BaseRoomDao functions and changed BaseEntity to an interface
appwise-labs/AndroidCore pull request #29
Opened 2021-03-30 13:40 UTC by SibertSchurmans

2021-03-31 14:50 UTC, Jesse-Appwise approved these changes

2021-04-02 09:26 UTC, Jesse-Appwise requested changes
https://github.com/appwise-labs/AndroidCore/issues/34

2021-04-07 09:53 UTC, Jesse-Appwise approved these changes
Using `open` to define the @Transition functions with bodies, makes the previous change request obsolete. Good job with the Dao's @SibertSchurmans 😉

2021-04-12 10:52 UTC, dieter115 approved these changes

2021-04-19 13:01 UTC, ChristianoBolla-Appwise approved these changes

2021-04-19 13:01 UTC, ChristianoBolla-Appwise approved these changes

2021-04-19 13:03 UTC, merged